//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Owner { get; set; }
        public int IDStatus { get; set; }
        public int IDType { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
